// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "jquery"
import "jquery_ujs"
import "login/login"
import "home/home"
import "home/age_range_slider"
import "home/images"
// import "./channels"
// import "trix"
// import "@rails/actiontext"
import "flowbite"
